---
valhalla_repo_url: "# Retrieve from Vault: secret/data/valhalla → git_repo_url"
valhalla_install_dir: "/opt/valhalla"
valhalla_user: "deploy"
valhalla_domain: "{{ vault_domain }}" # Vault: secret/data/valhalla → domain
valhalla_dns_servers:
  - "{{ vault_dns_1 }}" # Vault: secret/data/valhalla → dns_server_1
  - "{{ vault_dns_2 }}" # Vault: secret/data/valhalla → dns_server_2
valhalla_firewall_ports:
  - 80/tcp
  - 443/tcp
  - 3080/tcp
  - 3081/tcp
  - 9090/tcp
  - 3083/tcp
